version: "3" # Ensure a space after the colon
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
  app:
    image: my-node-app
    ports: # Correct key should be 'ports' (plural)
      - "1300:3000" # List item requires indentation, and quotes are good practice for port mappings
